In [7]:
import numpy as np

In [4]:
# python list
list1 = [11,2,3,4,5]
print(list1)
print(list1[0])

[11, 2, 3, 4, 5]
11


In [6]:
# list 
list2 = [0,1,3,'Hello', 'Data', [True, False]] 
print(list2)

[0, 1, 3, 'Hello', 'Data', [True, False]]


In [8]:
# ndarray = n-dimensional array

In [11]:
array1 = np.array(list1)
array1

array([11,  2,  3,  4,  5])

In [15]:

array1.shape # number of items in this array

(5,)

In [16]:
# range 
array2 = np.arange(10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# range 
array2 = np.arange(2,10) 
array2

array([2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# range 
array2 = np.arange(5,36,5) # np.arange(initial, end_point, difference) 
array2

array([ 5, 10, 15, 20, 25, 30, 35])

In [26]:
# zeors
np4 = np.zeros(10) # point zeros in nth number.   
np4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
np5 = np.zeros((2,5)) # (dimention, total item in each dimention)
np5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np5 = np.zeros((3,5)) # (dimention, total item in each dimention)
np5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
# full 
np6 = np.full((10),6) # syntex((number of total_items),the item)  
print(np6)

[6 6 6 6 6 6 6 6 6 6]


In [34]:
# full 
np6 = np.full((5),3) # syntex((number of total_items),the item)  
print(np6)

[3 3 3 3 3]


In [38]:
# multidimentional full 
np7 = np.full((2,10),5) # syntex: full((number of dimention, number of items), the item)
np7

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [39]:
# multidimentional full 
np7 = np.full((2,5),3) # syntex: full((number of dimention, number of items), the item)
np7

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [40]:
# convert list to array 
list1 = [10,20,30]
array12 = np.array(list1) 
array12 

array([10, 20, 30])