Numpy Excercise, WScube 1 Hr tutorial.

In [2]:
import numpy as np

In [3]:
# list 
l1 = [20,30,40]
l2 = [50,60,70] 
print(l1+l2)

[20, 30, 40, 50, 60, 70]


In [5]:
# list 
l2*2 

[50, 60, 70, 50, 60, 70]

In [8]:
# numpy array
a = np.array([20,30,40])
b = np.array([30,20,10]) 
print(a+b)

[50 50 50]


In [7]:
a*2

array([40, 60, 80])

Array can not take multiple data type 

In [10]:
# one string data makes all other data into string .
c = np.array([20,30,'4'])
c

array(['20', '30', '4'], dtype='<U21')

Numpy takes less memory in memory 

In [12]:
a = np.array([20,30,40])
a

array([20, 30, 40])

In [14]:
l1 = [20,30,40]
l1

[20, 30, 40]

-- Multi Dimantional Array -- 

In [17]:
ar_d = np.array ([[10,20,30,40],[50,60,70,80]]) # two raws and two column 

In [18]:
ar_d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [19]:
a = np.array([20,30,40,50,60,70])
a[0:3]

array([20, 30, 40])

In [20]:
a[0:]

array([20, 30, 40, 50, 60, 70])

In [21]:
a[:]

array([20, 30, 40, 50, 60, 70])

In [22]:
a[:5]

array([20, 30, 40, 50, 60])

In [23]:
a[2:3]

array([40])

In [24]:
a[0:2]

array([20, 30])

In [27]:
ar2 = np.array([[10,20,30,40],[30,60,90,95]])
ar2[0:2,0:2]

array([[10, 20],
       [30, 60]])

In [28]:
ar2[0,1:3]

array([20, 30])

In [29]:
ar2[1,1:3]

array([60, 90])

In [32]:
ar2 = np.array([[10,20,30,40],[30,60,90,95],[15,25,35,45]])
ar2[2,1:3]

array([25, 35])

In [33]:
ar2 = np.array([[10,20,30,40],[30,60,90,95],[15,25,35,45]])
ar2[2,1]

np.int64(25)

In [35]:
np.shape(ar2) # rows and column 

(3, 4)

In [37]:
np.size(ar2) # total 12 elements. 

12

In [39]:
np.ndim(ar2) # number of dimention. 

2

In [41]:
ar2.dtype # data type 

dtype('int64')