Mathematical Operations 

In [1]:
import numpy as np 

In [2]:
arr = np.array([30,10,20,50])

In [3]:
arr2 = np.array([10,10,10,5]) 

In [4]:
print(arr+arr2)

[40 20 30 55]


In [5]:
np.add(arr,arr2)

array([40, 20, 30, 55])

In [11]:
arr = np.array([30,10,20,50])
arr2 = np.array([10,10,10,5])
print(arr-arr2) 
print(np.subtract(arr2,arr))
print(np.divide(arr,arr2))

[20  0 10 45]
[-20   0 -10 -45]
[ 3.  1.  2. 10.]


In [12]:
arr = np.array([30,10,20,50])
arr2 = np.array([2]) 
print(np.pow(arr,arr2))

[ 900  100  400 2500]
