# Numpy 

In [2]:
import numpy as np

## Introduction
Numpy is a powerful library in Python used for numerical computing. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures efficiently.

### time consume    

In [50]:
%timeit [j*2 for j in range(20)]

1.01 μs ± 145 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [51]:
# numpy array time consume
%timeit np.arange(2)*2

2.39 μs ± 561 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


## array
In Numpy, arrays can have multiple dimensions. The most common types of arrays are:
**1-Dimensional Array (1D Array)**: This is a simple array that contains a single row or column of elements. 

**there are 1,2 and 3 dimension array in numpy**

Topic:
1. Creating Arrays
2. dimentional array
3. create arrays with specific values
4. create arrays with range of values
5. create diagonal arrays
6. arithmetic operations on arrays (min, max, sqrt, sin, cos, tan, log, exp, cumsum etc)

### Phase 1

In [96]:
a1 = np.array([1,2,3,4,5,6])

a1

array([1, 2, 3, 4, 5, 6])

In [97]:
type(a1)

numpy.ndarray

In [98]:
print(a1)

[1 2 3 4 5 6]


In [99]:
print(a1.shape)

(6,)


In [100]:
l = []

for i in range (4):
    l.append(i)

print(l)

[0, 1, 2, 3]


In [101]:
print(a1.ndim) # number of dimensions in this array.

1


In [102]:
# array with zeros

ar_zeros = np.zeros(4)
print(ar_zeros)

[0. 0. 0. 0.]


In [103]:
# array with zeros in  two dimension
ar_zeros_2d = np.zeros((3,4))
print(ar_zeros_2d)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [104]:
# array with 1 dimenssion
ar_ones = np.ones(5)
print(ar_ones)

[1. 1. 1. 1. 1.]


In [105]:
ar_empty = np.empty(5)
print(ar_empty)
print(len(ar_empty))

[1. 1. 1. 1. 1.]
5


In [106]:
ar_range = np.arange(10)
print(ar_range)

[0 1 2 3 4 5 6 7 8 9]


In [107]:
# diagonal array
ar_diag = np.diag([1,2,3,4,5])
print(ar_diag)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [108]:
# diagonal array with 1 
ar_diag_1 = np.eye(4)
print(ar_diag_1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [109]:
# linspace array

ar_lin = np.linspace(0,20, num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


### Array  - Data type

In [110]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
print(arr)

int32
[1 2 3 4 5]


In [111]:
arr2 = np.array(['A','B','C'])
print(arr2.dtype)
print(arr2)

<U1
['A' 'B' 'C']


In [112]:
arr3 = np.array([1,2,3,4.0,5,  'A', 'B', 'C', True, False])
print(arr3.dtype)
print(arr3)

<U32
['1' '2' '3' '4.0' '5' 'A' 'B' 'C' 'True' 'False']


In [113]:
arr4 = np.array([1,2,3,4,5], dtype='float64')
print(arr4.dtype)
print(arr4)

float64
[1. 2. 3. 4. 5.]


### Array - Arithmatic Operations

In [114]:
ar = np.array([1,2,3,4,5, 55, 23,12,51])
print(ar)

[ 1  2  3  4  5 55 23 12 51]


In [115]:
print("main array: ", ar)
print(ar+2)
print(ar-2)
print(ar*2)
print(ar/2)
print(ar**2)
print(ar%2)

main array:  [ 1  2  3  4  5 55 23 12 51]
[ 3  4  5  6  7 57 25 14 53]
[-1  0  1  2  3 53 21 10 49]
[  2   4   6   8  10 110  46  24 102]
[ 0.5  1.   1.5  2.   2.5 27.5 11.5  6.  25.5]
[   1    4    9   16   25 3025  529  144 2601]
[1 0 1 0 1 1 1 0 1]


In [116]:
print(np.sqrt(ar))

[1.         1.41421356 1.73205081 2.         2.23606798 7.41619849
 4.79583152 3.46410162 7.14142843]


In [117]:
print(ar.T)  # transpose of the array

[ 1  2  3  4  5 55 23 12 51]


In [118]:
aa1 = np.array([10,20,30,40,50])
aa2 = np.array([1,2,3,4,5])
print(aa1+aa2)


[11 22 33 44 55]


In [119]:
print(aa1*aa2)

[ 10  40  90 160 250]


In [120]:
# reciprocal of array elements
print(1/aa1)

[0.1        0.05       0.03333333 0.025      0.02      ]


In [121]:
ar = np.array([1,2,3,4,5, 55, 23,12,51])
print(ar)

[ 1  2  3  4  5 55 23 12 51]


In [122]:
print(ar+5)

[ 6  7  8  9 10 60 28 17 56]


In [123]:
print(ar.size) # total number of elements in this array.
print(ar.itemsize) # size of each element in bytes.
print(ar.nbytes) # total size of array in bytes.

9
4
36


In [124]:
# min, max and their position
print(ar)
print("Minimum value in array:", ar.min())
print("Maximum value in array:", ar.max())
print("Index of Minimum value in array:", ar.argmin())
print("Index of Maximum value in array:", ar.argmax())

[ 1  2  3  4  5 55 23 12 51]
Minimum value in array: 1
Maximum value in array: 55
Index of Minimum value in array: 0
Index of Maximum value in array: 5


In [125]:
var1 = np.array([[1,2,3], [5,3,2]])
print(var1)
print(var1.shape)
print(var1.ndim)
print(var1.size)
print(var1.dtype)
print(var1.itemsize)
print(var1.nbytes)
print(var1.T)  # transpose of array

[[1 2 3]
 [5 3 2]]
(2, 3)
2
6
int32
4
24
[[1 5]
 [2 3]
 [3 2]]


In [126]:
print(var1)
print(var1.max())

[[1 2 3]
 [5 3 2]]
5


In [127]:
print(np.min(var1, axis=0))  # column wise minimum
print(np.min(var1, axis=1))  # row wise minimum

[1 2 2]
[1 2]


In [128]:
print(np.max(var1, axis=0))  # column wise maximum
print(np.max(var1, axis=1))  # row wise maximum

[5 3 3]
[3 5]


In [129]:
var2 = np.array([9,4,25, 2,36])
print(var2)
print(np.sqrt(var2))

[ 9  4 25  2 36]
[3.         2.         5.         1.41421356 6.        ]


In [130]:
print(np.min(var2)) # minimum value in the array
print(np.max(var2)) # maximum value in the array

2
36


In [131]:
var3 = np.array([0, 30, 45, 60, 90])
print(np.sin(var3))
print(np.cos(var3))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


In [132]:
print(var3)
print(np.cumsum(var3))

[ 0 30 45 60 90]
[  0  30  75 135 225]


### Array Shape and Reshape

In [133]:
ar = np.array([1,2,3,4])
ar2 = ar

print(ar)
print(ar2)
# no change in original array
ar2 = ar2+5
print(ar2)
print(ar)

[1 2 3 4]
[1 2 3 4]
[6 7 8 9]
[1 2 3 4]


In [134]:
# Reshape array
ar = np.arange(6)
print(ar)
print(ar.ndim)
print()

ar_reshaped = ar.reshape(2,3)
print(ar_reshaped)
print(ar_reshaped.ndim)

[0 1 2 3 4 5]
1

[[0 1 2]
 [3 4 5]]
2


In [135]:
# get back to one dimension
one_shaped = ar_reshaped.reshape(-1)
print(one_shaped)
print(one_shaped.ndim)


[0 1 2 3 4 5]
1


### Array - Copy vs View

In [136]:
var = np.array([1,2,3,4])

var2 = np.array([1,2,3,10])

c_var = var.copy()

print(var)
print(c_var)


[1 2 3 4]
[1 2 3 4]


In [137]:
print(c_var)
c_var = c_var+1
print(c_var)
print(var)

[1 2 3 4]
[2 3 4 5]
[1 2 3 4]


In [138]:
x = np.array([2,4,6])

x_view = x.view()
print(x)
print(x_view)

[2 4 6]
[2 4 6]


In [139]:
print(x_view)
x_view[0]= 20
print(x_view)
print('original x:',x)

[2 4 6]
[20  4  6]
original x: [20  4  6]


## Array Broadcasting


* dimension must be same for broadcasting
* if dimention not same, then column must same.
* if not same dimension error will occur
* to make same dimension we can use reshape function
* broadcasting is used to perform arithmetic operations on arrays of different shapes
* numpy automatically expands the smaller array to match the shape of the larger array during the operation
* this is useful for performing operations without explicitly reshaping the arrays
* broadcasting follows specific rules to determine how the arrays are expanded
* if the arrays have a different number of dimensions, the shape of the smaller-dimensional array is padded with ones on the left side until both shapes have the same length

### Basic: broadcasting

In [49]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])
# wrong - broadcasting
print(var1+var2)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3, 10])
# wrong - broadcasting
print(var1+var2)

[ 2  4  6 14]


In [ ]:
var1 = np.array([1,2,3,4])
var2 = np.array([[1],[2],[3],[4]])
print(var2.ndim)
print(var2)
# correct dimention
print(var1+var2)


2
[[1]
 [2]
 [3]
 [4]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]


## Array Indexing and Slicing

In [140]:
var1 = np.array([1,2,3,4,5,6])

print(var1[0])
print(var1[2])
print(var1[-1])
print(var1[1:4])
print(var1[::2])  # step size 2

1
3
6
[2 3 4]
[1 3 5]


In [141]:
print(var1)
print(var1[1:5])
print(var1[1:5:2])  # step size 2


[1 2 3 4 5 6]
[2 3 4 5]
[2 4]


## Array Iteration

### Basic: Iterating Arrays

In [142]:
x = np.array([11,22,33,44,55])
for i in x:
    print(i)

11
22
33
44
55


In [144]:
x[4]=66
print(x)

[11 22 33 44 66]


In [147]:
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(y)
print()
for i in y:
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]
[4 5 6]
[7 8 9]


In [148]:
for i in y:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


### Array Function for iteration

In [150]:
xy = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(xy)
print()

for i in np.nditer(xy):
    print(i)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1
2
3
4
5
6
7
8
9


In [154]:
xy = np.array([[1,2,3], [4,5,6], [7,8,9]])

for i in np.nditer(xy, flags=[b'buffered'], op_dtypes=['S']): # convert to string 
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'


In [153]:
for i, d in np.ndenumerate(xy): # i = index, d = data, get value with index
    print(i, d)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


## Array Joining and Splitting

### Joining Arrays

In [156]:
x1 = np.array([10,15,20, 35])
x2 = np.array([5,10,15,25])

#join 1D arrays
x3 = np.concatenate((x1,x2))
print(x3)

[10 15 20 35  5 10 15 25]


In [157]:
xx = np.array([[1,2,3], [4,5,6]])
xy = np.array([[7,8,9], [10,11,12]])
# join 2D arrays along rows (axis=0)
xz = np.concatenate((xx,xy), axis=0)
print(xz)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [158]:
xx = np.array([[1,2,3], [4,5,6]])
xy = np.array([[7,8,9], [10,11,12]])
# join 2D arrays along columns (axis=1)
xz = np.concatenate((xx,xy), axis=1)
print(xz)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [161]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([6,7,8,9,10])

x_new = np.stack((x1,x2))
print(x_new)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([6,7,8,9,10])

x_new = np.vstack((x1,x2)) # column wise stacking
print(x_new)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [165]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([6,7,8,9,10])

x_new = np.dstack((x1,x2)) # height wise stacking
print(x_new)

[[[ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]
  [ 5 10]]]


In [164]:
x1 = np.array([1,2,3,4,5])
x2 = np.array([6,7,8,9,10])

x_new = np.hstack((x1,x2)) # row wise stacking
print(x_new)

[ 1  2  3  4  5  6  7  8  9 10]


### Splitting Arrays

In [166]:
x = np.array([1,2,3,4,5,6])
print(x)
# split into 3 parts
ar = np.array_split(x, 3)
print(ar)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [167]:
# split into 4 parts
ar = np.array_split(x, 4)
print(ar)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [168]:
# split into 2 parts
a1, a2 = np.array_split(x, 2)
print(a1)
print(a2)

[1 2 3]
[4 5 6]


In [169]:
# split 2d array
x2d = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(x2d)
# split into 3 parts along columns
ar = np.array_split(x2d, 3, axis=1)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[array([[1, 2],
       [7, 8]]), array([[ 3,  4],
       [ 9, 10]]), array([[ 5,  6],
       [11, 12]])]


## Numpy Function 
* sort, searchsorted, where, shuffle, unique, resize, flatten, tolist, tostring, fromstring, fromfile, fill, itemsize, nditer, ndindex, ravel, transpose, squeeze, sum, mean, std, var, min, max, orgmin, argmin, argmax, cumsum, cumprod, diff, nonzero, argwhere, sort, argsort, lexsort, quantile, percentile, round, astype, copy, view etc

### basic functions

In [2]:
import numpy as np

In [8]:
# to see position of a value
x = np.array([11,20,50,30,40, 55 ,50, 65,60,70,80,90])
result = np.where(x==50)
print(result)

(array([2, 6], dtype=int64),)


In [10]:
result = np.where(x%2 != 0)
print(result)


(array([0, 5, 7], dtype=int64),)


In [13]:
var1 = np.array([1,2,3,4, 7, 8,9,10])
pos = np.searchsorted(var1,5)
print(pos) # in this position you can insert 5 to keep the array sorted.
pos2 = np.searchsorted(var1, 8.5)
print(pos2)

4
6


### Sort

In [16]:
var = np.array([11,1,4,2,6,33,12,1])
print(np.sort(var))

[ 1  1  2  4  6 11 12 33]


In [15]:
var_ch = np.array(['banana', 'apple', 'cherry', 'date'])
print(np.sort(var_ch))

['apple' 'banana' 'cherry' 'date']


### Shuffle function

In [31]:
var3 = np.array([1,2,3,4,5,3,2,1,4,5,6,7,8,7,6])
var_sf = np.random.shuffle(var3) # make it shuffle.
print(var3)

[1 3 4 2 5 6 7 2 3 6 5 4 7 1 8]


### Unique function

In [38]:
var4 = np.array([1,2,3,4,1,1,4,25,25,25])
var_unique =  np.unique(var4)
print(var_unique)

[ 1  2  3  4 25]


### Resize function

In [42]:
var2 = np.array([12,3,4,5,1,5])
var2_resized = np.resize(var2, (2,3))
print(var2_resized)

[[12  3  4]
 [ 5  1  5]]


### Raven function

## Intro